services:
  - type: web
    name: portfolio-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://aryangupta9352_db_user:akki@cluster0.g5xl0p1.mongodb.net/portfolio?retryWrites=true&w=majority&appName=Cluster0
      - key: CLIENT_URL
        value: https://portfolio-full-stack-assignment.vercel.app
    healthCheckPath: /
    autoDeploy: true         # Auto-redeploy when you push to GitHub
